# Generated by Django 6.0.3 on 2026-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('target_audience', models.CharField(choices=[('all', 'All'), ('owners', 'Owners'), ('residents', 'Residents'), ('board', 'Board')], default='all', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('expires_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('water', 'Water'), ('fire', 'Fire'), ('security', 'Security'), ('weather', 'Weather'), ('other', 'Other')], default='other', max_length=10)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
