# Generated by Django 6.0.3 on 2026-03-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('notification_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued')], default='queued', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.community')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_reminder_days_before', models.IntegerField(default=7, help_text='Days before due date to send reminder')),
                ('assessment_second_reminder_days', models.IntegerField(default=3, help_text='Days before due date for second reminder')),
                ('overdue_reminder_frequency_days', models.IntegerField(default=7, help_text='How often to remind about overdue assessments')),
                ('meeting_reminder_days_before', models.IntegerField(default=3, help_text='Days before meeting to send reminder')),
                ('meeting_reminder_hours_before', models.IntegerField(default=2, help_text='Hours before meeting for day-of reminder')),
                ('violation_cure_reminder_days_before', models.IntegerField(default=3, help_text='Days before cure deadline to remind')),
                ('work_order_stale_days', models.IntegerField(default=14, help_text='Days before flagging a work order as stale')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedule', to='core.community')),
            ],
            options={
                'ordering': ['community__name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_reminders', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='email', max_length=10)),
                ('overdue_notices', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='both', max_length=10)),
                ('violation_notices', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='email', max_length=10)),
                ('work_order_updates', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='email', max_length=10)),
                ('meeting_reminders', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='email', max_length=10)),
                ('arb_updates', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='email', max_length=10)),
                ('announcements', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='email', max_length=10)),
                ('emergency_alerts', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('none', 'None')], default='both', max_length=10)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name'],
                'unique_together': {('community', 'user')},
            },
        ),
    ]
