# Generated by Django 6.0.3 on 2026-03-24 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('board', 'Board Meeting'), ('annual', 'Annual Meeting'), ('special', 'Special Meeting'), ('committee', 'Committee Meeting')], default='board', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('time_allotted_minutes', models.IntegerField(default=10)),
                ('item_type', models.CharField(choices=[('discussion', 'Discussion'), ('vote', 'Vote'), ('report', 'Report'), ('other', 'Other')], default='discussion', max_length=20)),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_minutes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_minutes', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meetings.meeting')),
            ],
            options={
                'verbose_name_plural': 'minutes',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('vote_type', models.CharField(choices=[('board_vote', 'Board Vote'), ('homeowner_vote', 'Homeowner Vote')], default='board_vote', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('requires_quorum', models.BooleanField(default=True)),
                ('quorum_percentage', models.IntegerField(default=51)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.community')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=10)),
                ('cast_date', models.DateTimeField(auto_now_add=True)),
                ('is_proxy', models.BooleanField(default=False)),
                ('proxy_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_ballots', to='properties.owner')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='meetings.vote')),
            ],
            options={
                'ordering': ['-cast_date'],
                'unique_together': {('vote', 'voter')},
            },
        ),
    ]
