# Generated by Django 6.0.3 on 2026-03-24 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family'), ('townhouse', 'Townhouse'), ('condo', 'Condo'), ('lot', 'Lot')], default='single_family', max_length=20)),
                ('square_footage', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.CharField(blank=True, default='', max_length=50)),
                ('parking_spots', models.IntegerField(default=0)),
                ('has_garage', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.community')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['unit_number'],
                'unique_together': {('community', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('mailing_address', models.CharField(blank=True, default='', help_text='If different from property address', max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('ownership_start_date', models.DateField(blank=True, null=True)),
                ('ownership_end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='core.community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownerships', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='properties.property')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_owner', models.BooleanField(default=False)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('vehicle_make', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_color', models.CharField(blank=True, default='', max_length=30)),
                ('license_plate', models.CharField(blank=True, default='', max_length=20)),
                ('pet_type', models.CharField(blank=True, default='', max_length=50)),
                ('pet_breed', models.CharField(blank=True, default='', max_length=50)),
                ('pet_name', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='core.community')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='properties.property')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('spot_type', models.CharField(choices=[('standard', 'Standard'), ('handicap', 'Handicap'), ('reserved', 'Reserved'), ('guest', 'Guest')], default='standard', max_length=20)),
                ('is_assigned', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='core.community')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parking_spots', to='properties.property')),
            ],
            options={
                'ordering': ['spot_number'],
                'unique_together': {('community', 'spot_number')},
            },
        ),
    ]
