# Generated by Django 6.0.3 on 2026-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARBComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ARB Comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARBRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('exterior_paint', 'Exterior Paint'), ('fence', 'Fence'), ('landscaping', 'Landscaping'), ('structure', 'Structure'), ('roof', 'Roof'), ('solar', 'Solar'), ('window', 'Window'), ('door', 'Door'), ('other', 'Other')], default='other', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('plans_file', models.FileField(blank=True, null=True, upload_to='arb_plans/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='arb_photos/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('conditions', models.TextField(blank=True, default='')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ARB Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
