# Generated by Django 6.0.3 on 2026-03-24 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architectural', '0001_initial'),
        ('core', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arbcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arb_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbrequest',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arb_requests', to='core.community'),
        ),
        migrations.AddField(
            model_name='arbrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arb_requests', to='properties.owner'),
        ),
        migrations.AddField(
            model_name='arbrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arb_requests', to='properties.property'),
        ),
        migrations.AddField(
            model_name='arbrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_arb_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='architectural.arbrequest'),
        ),
    ]
