# Generated by Django 6.0.3 on 2026-03-24 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('date_observed', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('notice_sent', 'Notice Sent'), ('cured', 'Cured'), ('escalated', 'Escalated'), ('fined', 'Fined'), ('closed', 'Closed'), ('appealed', 'Appealed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('cure_deadline', models.DateField(blank=True, null=True)),
                ('cured_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_violations', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.community')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='properties.property')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('waived', 'Waived'), ('appealed', 'Appealed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='core.community')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='violations.violation')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_date', models.DateField()),
                ('reason', models.TextField()),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('overturned', 'Overturned'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('decided_date', models.DateField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='core.community')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_decisions', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='properties.owner')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='violations.violation')),
            ],
            options={
                'ordering': ['-filed_date'],
            },
        ),
        migrations.CreateModel(
            name='ViolationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('first_warning', 'First Warning'), ('second_warning', 'Second Warning'), ('final_notice', 'Final Notice'), ('fine_notice', 'Fine Notice'), ('hearing_notice', 'Hearing Notice')], max_length=20)),
                ('sent_date', models.DateField()),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('mail', 'Mail'), ('both', 'Both')], default='email', max_length=10)),
                ('content', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_notices', to='core.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='violations.violation')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('default_fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('property_maintenance', 'Property Maintenance'), ('parking', 'Parking'), ('noise', 'Noise'), ('pets', 'Pets'), ('architectural', 'Architectural'), ('landscaping', 'Landscaping'), ('trash', 'Trash'), ('other', 'Other')], default='other', max_length=30)),
                ('cure_period_days', models.IntegerField(default=14)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_types', to='core.community')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('community', 'name')},
            },
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='violations.violationtype'),
        ),
    ]
